basePath: /
definitions:
  models.Request:
    properties:
      headers:
        additionalProperties:
          type: string
        type: object
      method:
        type: string
      url:
        type: string
    type: object
  models.Response:
    properties:
      headers:
        additionalProperties:
          type: string
        type: object
      id:
        type: string
      length:
        type: integer
      status:
        type: integer
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a simple server for proxying HTTP requests
  title: HTTP Proxy Service
  version: "1.0"
paths:
  /health:
    get:
      consumes:
      - application/json
      description: Check if the service is running.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Health check
      tags:
      - health
  /proxy:
    post:
      consumes:
      - application/json
      description: Proxy an HTTP request to the specified URL.
      parameters:
      - description: Proxy request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.Request'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Response'
      summary: Proxy request
      tags:
      - proxy
swagger: "2.0"
